<?php
$base_url = $this->basePath();
?>
<div class="row banner_2_login">
    <div class="col-lg-offset-2 col-lg-8 col-md-12 col-xs-12 font-principal">
        <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12"></div>
        <div><br><br><br></div>
        <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 hidden-xs hidden-sm">
            <p>
                <img class="img-responsive center-block" src="<?php echo $base_url.$apps_var['img_logo_concurso']; ?>"/>
            </p>
        </div>
        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12">
            <div class="box_login">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><h2 class="text-center"><b><?php echo $apps_var['name_app']; ?></b></h2><br></div>        
                <div class="center_div">
                    <form id="usuario_sec_frm_login" method="POST" action="<?php echo $this->url('usuario/sec', array('action' => 'validate')); ?>" class="form-horizontal">

                        <div class="form-group">
                            <label class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lbl_login_">Documento de identidad:</label>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <input type="text" class="form-control input_frm" id="usuario_sec_documento" name="usuario_sec_documento" autocomplete="off" maxlength="<?php echo $apps_usuario['num_caracteres']['documento_identidad']['max'] ;?>" placeholder="DNI/CE">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword" class="col-lg-4 col-md-4 col-sm-6 col-xs-12 lbl_login_">Contrase&ntilde;a:</label>
                            <label for="inputPassword" class="col-lg-8 col-md-8 col-sm-6 col-xs-12"><b><a href="<?php echo $this->url('usuario/sec', array('action' => 'recuperar')); ?>">&iquest;Olvid&oacute; su contrase&ntilde;a?</a>&nbsp;&nbsp;&nbsp; </b></label>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <input type="password" id="usuario_sec_password" name="usuario_sec_password" class="form-control input_frm" autocomplete="off" maxlength="<?php echo $apps_usuario['num_caracteres']['contrasenias']['max'] ;?>" placeholder="CONTRASEÑA">
                            </div>
                        </div>

                        <?php
                        if ($apps_usuario['num_caracteres']['captcha']['enabled'] === true) {
                            ?>
                            <div class="form-group text-right">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <img id="ref_login" src="<?php echo $base_url ?>/usuario/captcha/logincaptcha?rnd=<?php echo rand(); ?>"/>
                                    <a href="javascript:" onclick="refresh_login()" data-toggle="tooltip" title="Actualizar" ><span class="glyphicon glyphicon-refresh"></span></a>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-7 col-md-7 col-sm-7 col-xs-12 lbl_login_"  for="inputCodigo" >C&oacute;digo de la imagen:</label>
                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                    <input type="text" class="form-control input_frm" id="usuario_sec_captcha_login" name="usuario_sec_captcha_login" autocomplete="off" maxlength="<?php echo $apps_usuario['num_caracteres']['captcha']['tamano_codigo'] ;?>" style="text-transform:uppercase">
                                </div>
                            </div>
    <?php
}
if (count($msgs) > 0) {
    foreach ($msgs as $msg) {
        echo($msg);
    }
}
?>

                        <div class="form-group text-right">
                            <div class="col-lg-offset-6 col-md-offset-6 col-sm-offset-0 col-xs-offset-0 col-lg-6 col-md-6 col-sm-12  col-xs-12">
                                <button id="usuario_sec_login" type="submit" class="btn col-lg-12 col-md-12 col-sm-12 col-xs-12 btn-rojo">Ingresar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>