<?php
$base_url = $this->basePath();
?>
<div class="col-sm-12 col-md-12 text-center well">
    <div class="login col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3">
        <h3 class="pull-left">INICIAR SESION</h3>
        <br>
        <img src="<?php echo $base_url; ?>/img/interrogacion.png" class="signo-inte">
        <form id="usuario_sec_frm_login" class="frmlogin" method="POST" action="<?php echo $this->url('usuario/sec', array('action' => 'validate')); ?>" class="form-horizontal" autocomplete="off">
            <div class="row">
                <div class="form-group" >
                    <label for="txtuser" class="col-md-3 control-label">USUARIO</label>
                    <div class="col-md-12">
                        <input type="text" class="form-control input_frm" id="usuario_sec_documento" name="usuario_sec_documento" autocomplete="off" maxlength="15" placeholder="USUARIO">
                    </div>
                </div>
            </div>	
            <div class="row">
                <div class="form-group">
                    <label for="txtpass" class="col-md-3 control-label">CONTRASEÑA</label>
                    <div class="col-md-12">
                        <input type="password" id="usuario_sec_password" name="usuario_sec_password" class="form-control input_frm" autocomplete="off" maxlength="20" placeholder="CONTRASEÑA">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-1"></div>
                    <div class="col-md-5" style="text-align: left;">  <img id="ref_login" src="<?php echo $base_url ?>/usuario/captcha/logincaptcha?rnd=<?php echo rand(); ?>"/></div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-1"><a href="javascript:" javascript: class="btn btn-xs btn-default btn-refresh"><i class="glyphicon glyphicon-refresh"></i></a></div>
                    <div class="col-md-5"><input type="text" class="form-control input_frm" id="usuario_sec_captcha_login" name="usuario_sec_captcha_login" autocomplete="off" maxlength="3" style="text-transform:uppercase"></div>
                </div>
            </div>
            <div class="row">
                <button type="submit" id="usuario_sec_login" class="btn btn-black">INGRESAR&nbsp;&nbsp;<i class="glyphicon glyphicon-chevron-right"></i></button>
                <!--<button id="usuario_sec_login" type="submit" class="btn col-lg-12 col-md-12 col-sm-12 col-xs-12 btn-rojo">Ingresar</button>-->
            </div>
            <div class="clearfix"></div>
        </form>
    </div>


    <div class="clearfix"></div>   
</div>
<div class="clearfix"></div>