<?php
echo $this->doctype();
$base_url   = $this->basePath();
$apps_var   = $this->apps_var;
$usuario    = $this->users_acl->rows;
$cambio_config = $this->cambio_config;
?>
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle($apps_var['app_title'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('js/lib/jqgrid/css/ui.jqgrid-bootstrap.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-datepicker.css'))
        ?>        

        <script type="text/javascript">
            var root = "<?php echo $base_url; ?>";
            var min_clave   = <?php echo $cambio_config['caracteres_min_clave']; ?>;
            var max_clave   = <?php echo $cambio_config['caracteres_max_clave']; ?>;
            var min_dni     = <?php echo $cambio_config['caracteres_min_dni']; ?>;
            var max_dni     = <?php echo $cambio_config['caracteres_max_dni']; ?>;
            var max_correo  = <?php echo $cambio_config['caracteres_max_correo']; ?>;
        </script>
        <!-- Scripts -->

    </head>
    <body class="body_bg">
        <div class="row row-fluid">
            <div class="col-md-12 banner_top_titulo">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <img class="img-responsive center-block img_logo_evdocente" src="<?php echo $base_url; ?>/img/indago.png"/>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <a target="_blank" href="http://www.minedu.gob.pe/" class="text-center">
                        <img class="img-responsive center-block" src="<?php echo $base_url; ?>/img/logo_ministerio_educacion.gif"/>
                    </a>
                </div>
            </div>
        </div>
        <div class="row dashboard_barra_top">
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 text-center" id="tbi_name_display">
                Bienvenido(a): <?php echo $usuario->display_name; ?>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-12 col-xs-12  text-center">
                <?php
                    if (utf8_encode($usuario->fec_ultimo_acceso) === '')
                    {
                        echo 'Último acceso: ' . date("Y-m-d H:i:s");
                    }
                    else if (utf8_encode($usuario->fec_ultimo_acceso) === '-')
                    {
                        echo '';
                    }
                    else
                    {
                        echo 'Último acceso: ' . $usuario->fec_ultimo_acceso;
                    }
                ?>
                <input type="hidden" id="hdn_sesion_token" name="hdn_sesion_token" value="<?php echo $this->token_sesion; ?>" />
            </div>
            <?php
            $fecha_i = date($usuario->fec_ini_proceso);
            $fecha_i = date("Y-m-d", strtotime($fecha_i));
            $fecha_f = date('Y-m-d');
            $datetime1 = date_create($fecha_i);
            $datetime2 = date_create($fecha_f);
            $interval = date_diff($datetime2, $datetime1);
            ?>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12  text-center rojo_minedu" style="font-size: 16px;font-weight: bold;" >
                <?php
                if ($dashboard_config["opc_msje_app"] === true)
                {
                    if ($interval->format('%R%a') <= 0)
                    {
                        echo $usuario->dias_restantes;
                    }
                }
                ?>                
            </div>
            <div class="col-lg-2 col-md-6 col-sm-12 col-xs-12 text-center">
                <a id="btn_cerrar_sesion" href="<?php echo $this->url('usuario/sec', array('action' => 'logout')); ?>">Cerrar sesión</a>
            </div>
        </div>
        <div class="container-fluid">
            <?php echo $this->content; ?>
            <?php
            echo $this->headScript()
                    ->prependFile($this->basePath('js/app/menu_datos_usuario.js?v=' . md5(time())))
                    ->prependFile($this->basePath('js/app/menu_presentacion.js?v=' . md5(time())))
                    ->prependFile($this->basePath('js/app/menu_seleccion.js?v=' . md5(time())))
                    ->prependFile($this->basePath('js/lib/handlebars-v4.0.5.js'))
                    ->prependFile($this->basePath('js/app/menu.js?v=' . md5(time())))
                    ->prependFile($this->basePath('js/app/app.js?v=' . md5(time())))                    
                    ->prependFile($this->basePath('js/seleccion.js?v=' . md5(time())))                    
                    ->prependFile($this->basePath('js/util_seleccion.js?v=' . md5(time())))                    
                    ->prependFile($this->basePath('js/bootstrap-datepicker.min.js?v=' . md5(time())))
                    ->prependFile($this->basePath('js/lib/datepicker-locale-es.js'))
                    ->prependFile($this->basePath('js/lib/moment.js'))
                    ->prependFile($this->basePath('js/lib/safify.js'))
                    ->prependFile($this->basePath('js/lib/jqgrid/i18n/grid.locale-es.js'))
                    ->prependFile($this->basePath('js/lib/jqgrid/jquery.jqGrid.min.js'))
                    ->prependFile($this->basePath('js/lib/bootbox.min.js'))
                    ->prependFile($this->basePath('js/lib/kakashi.js'))
                    ->prependFile($this->basePath('js/lib/naruto.js'))
                    ->prependFile($this->basePath('js/lib/porigon.js'))
                    ->prependFile($this->basePath('js/lib/BaseXJS/jquery.filter_input.js'))
                    ->prependFile($this->basePath('js/lib/BaseXJS/jquery.commons.js'))
                    ->prependFile($this->basePath() . '/d.js?v=' . md5(time()))
                    ->prependFile($this->basePath('js/app/_strings.js'))
                    ->prependFile($this->basePath('js/lib/BaseXJS/BaseX.js'))
                    ->prependFile($this->basePath('js/bootstrap.min.js'))
                    ->prependFile($this->basePath('js/jquery.min.js'))
                    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ;
            ?>

        </div> <!-- /container -->
        <footer class="footer">
            <div class="container">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
                    <br />
                    <p class="text-muted footer_color">
                        Línea de atención al comité de evaluación<br />
                        <?php echo $apps_var['number_support1']; ?><br>
                    </p>
                    <!--<a href="mailto:evaluaciondocente.cpm@perueduca.pe">evaluaciondocente.cpm@perueduca.pe</a>-->
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
                    <br />
                    <p class="text-muted footer_color">
                        <?php echo date('Y'); ?> &copy; Todos los derechos reservados
                    </p>
                </div>
                <!--<div class="clearfix"></div>-->
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
        <!--<script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js"></script>-->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script type='text/javascript' src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
          <script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
        <![endif]-->
        <script>
<?php echo $apps_var['google_analytics_code']; ?>
        </script>
    </body>
</html>
