<?php
$base_url = $this->basePath();
?>
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="hero-unit center">
          <h1>Página no encontrada</h1>
          <br />
          <p>La página solicitada puede no estar disponible, haber cambiado de dirección (URL) o no existir.</p>
          <p>Con frecuencia es debido a algún error al escribir la dirección de la página (URL).</p>
          <a href="<?php echo $base_url.'/usuario/sec'; ?>" class="btn btn-naranja"><i class="icon-home icon-white"></i> Ir a la página de Inicio.</a>
        </div>
        <br />
        <br />
        <p></p>
    </div>
  </div>
</div>