<?php
$base_url = $this->basePath();

function detect()
{
    $browser = array("IE", "OPERA", "MOZILLA", "NETSCAPE", "FIREFOX", "SAFARI", "CHROME");
    $os = array("WIN", "MAC", "LINUX");

    # definimos unos valores por defecto para el navegador y el sistema operativo
    $info['browser'] = "OTHER";
    $info['os'] = "OTHER";

    # buscamos el navegador con su sistema operativo
    foreach ($browser as $parent)
    {
        $s = strpos(strtoupper($_SERVER['HTTP_USER_AGENT']), $parent);
        $f = $s + strlen($parent);
        $version = substr($_SERVER['HTTP_USER_AGENT'], $f, 15);
        $version = preg_replace('/[^0-9,.]/', '', $version);
        if ($s)
        {
            $info['browser'] = $parent;
            $info['version'] = $version;
        }
    }

    # obtenemos el sistema operativo
    foreach ($os as $val)
    {
        if (strpos(strtoupper($_SERVER['HTTP_USER_AGENT']), $val) !== false)
            $info['os'] = $val;
    }

    # devolvemos el array de valores
    return $info;
}

$info = detect();
?>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Login, registration forms">
        <meta name="author" content="">

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink()
                ->prependStylesheet($this->basePath('css_rd/bootstrap/320/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css_rd/font-awesome/css/font-awesome.css'))
                ->prependStylesheet($this->basePath('css_rd/app/header.css'))
                ->prependStylesheet($this->basePath('css_rd/app/footer_ini.css'))
                ->prependStylesheet($this->basePath('css_rd/app/body_ini.css'))
                ->prependStylesheet($this->basePath('css_rd/navbar.css'))
                ->prependStylesheet($this->basePath('css_rd/mix.css'));
        ?>


        <link href='https://fonts.googleapis.com/css?family=Product+Sans' rel='stylesheet' type='text/css'>
        <style type="text/css">
            .navbar { background-color: #14A3BD; height: 76px; }
        </style>


        <script>
            var root = '<?php echo $base_url; ?>';
        </script>
    </head>
    <body>
        <div id="wrapper">
            <?php
            if ($info["browser"] === "IE")
            {
                ?>
                <div class="row" style="background-color: #EDD0D0; border-color: #EDD0D0;height: 50px;text-align:center;"><h3 style="color:#CE141F !important;">Advertencia:  Este sitio web funciona mejor con Mozilla Firefox  y Chrome.</h3></div>
    <?php
}
?>
<?php ?>
            <div class="header">
                <div class="container">
                    <div class="col-md-12 col-md-offset-0">
                        <div class="col-xs-4 col-sm-6 col-md-6">
                            <img src="<?php echo $base_url; ?>/img/indago.png" class="sri" width="260px">
                        </div>

                        <div class="col-xs-2 col-sm-6 col-md-6">
                            <img src="<?php echo $base_url; ?>/img/logo.png" class="logo">
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>    
            </div>

            <div class="container section">
                <div class="row">
            <?php echo $this->content; ?>
                </div>  
            </div>  


<?php echo $this->inlineScript() ?>
        </div>
        <div class="footer">
            <div class="container">
                <div class="col-xs-3 col-sm-3 col-md-3 canales">
                    <!--                    <h3>© Derechos Reservados 2017 - MINEDU
                                        </h3>-->
                </div>
                <div class="col-xs-3 col-sm-3 col-md-2 telefono text-left">
                    <!--<h3><i class="fa fa-phone-square"></i> <span class="num-fono">615-5855</span> </h3>-->
                </div>
                <div class="col-xs-3 col-sm-4 col-md-5 correobox">
                    <!--                    <a href="mailto:demo@minedu.gob.pe" title="ofertaeducativa@minedu.gob.pe">
                                            <i class="fa fa-envelope"></i> <span class="correo">&nbsp;demo@minedu.gob.pe</span></a>-->
                    <h3>© Derechos Reservados 2017 - MINEDU
                    </h3>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-2 redes">
                    <div class="pull-right">
<!--                        <a href="#" id="icon-facebook" title="Facebook"><img src="<?php echo $base_url ?>/img/face.png" height="32" width="32"></a>
                        <a href="#" id="icon-twitter" title="Twitter"><img src="<?php echo $base_url ?>/img/twitter.png" height="32" width="32"> </a>-->
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </body>
    <?php
    echo $this->headScript()
            ->prependFile($this->basePath('js/lib/UsuarioJS/naruto.js'))
            ->prependFile($this->basePath('js/lib/UsuarioJS/kakashi.min.js'))
            ->prependFile($this->basePath('js/lib/UsuarioJS/bootbox.min.js'))
            ->prependFile($this->basePath('js_rd/jquery/203/jquery.min.js'))
            ->prependFile($this->basePath('js_rd/bootstrap/320/bootstrap.min.js'))
            ->prependFile($this->basePath('js/lib/UsuarioJS/login.js?v=' . md5(time())))
            ->prependFile($this->basePath('js/lib/porigon.js'))
            ->prependFile($this->basePath('js/lib/safify.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/lib/UsuarioJS/captcha.js'))
            ->prependFile($this->basePath('js/lib/BaseXJS/jquery.filter_input.js'))
            ->prependFile($this->basePath('js/lib/BaseXJS/jquery.validate.js'))
            ->prependFile($this->basePath('js/lib/BaseXJS/BaseX.js?v=' . md5(time())))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/app/_strings.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ;
    ?>
</html>
