<div id="navbar" class="col-sm-3 col-md-3">
<!--<div id="navbar" class="col-sm-3 col-md-3 navbar-collapse" style="background-color: white; padding: 20px;">-->
    <?php
    echo $this->partial('layout/_menu.phtml', [
        'users_acl' => $this->users_acl
    ]);
    ?>

</div>
<div class="col-sm-9 col-md-9">
    <div class="row">
        <div class="col-sm-12 col-md-12 main" style="background-color: white; margin-bottom: 100px;">
            <div id="workArea">
            </div>
        </div>
    </div>
</div>