<?php
$base_url = $this->basePath();
?>

<div id="div_presentacion" class="font-principal">
    
    <div id="div_titulo" class="row">
        <div class="titulo_principal col-lg-12">
            &nbsp;&nbsp;&nbsp;Material de ayuda
        </div>
    </div>
    
    <div id="div_datos" class="row">
        <div class="col-lg-12" style="margin-left: 25px;">  
            <br />
            <div>
                Estimado miembro de comité le presentamos el siguiente material de ayuda:
            </div>
            <br />
            <div>
                <a href="<?php echo $base_url . '/pdf_ins/ins_adjplazas.pdf' ?>" target="_blank">- Instructivo para el aplicativo de Adjudicación de Plazas.</a><br />
            </div>
            <br />
            <div>
                De tener alguna consulta, por favor comuníquese a la línea de atención al Comité de Evaluación (01) 615-5887 , de lunes a viernes de 8:30 am a 5:30 pm.
            </div>
            <br />
            <div>
                Más información en: <a href="<?php echo $apps_var['pagina_web']; ?>" target="_blank"><?php echo $apps_var['pagina_web']; ?></a>
            </div>
            <br />
        </div>
    </div>

</div>



