<?php
$date_ini = new DateTime(date($fec_ini_proc));
$date_fin = new DateTime(date($fec_fin_proc));
?>

<div id="div_consulta" class="font-principal">
    
    <div id="div_titulo" class="row">
        <div class="titulo_principal col-lg-12">
            &nbsp;&nbsp;&nbsp;<?php echo $apps_var['name_app']; ?>
        </div>
    </div>
    
    <div id="div_mensaje" class="row">
        <div class="col-lg-12">   
            <h3>
                El proceso de <?php echo $apps_var['name_app']; ?> inicia el <?php echo $date_ini->format('d-m-Y'); ?> y culmina el <?php echo $date_fin->format('d-m-Y'); ?>.
            </h3>
        </div>    
    </div>
    
</div>    