<ul class="nav nav-tabs3 nav-stacked" role="tablist">
    <li role="presentation" id="mnuInicio"          data-function-handle="menu_inicio">
        <a href="#" aria-controls="responsable" role="tab" data-toggle="tab">Inicio</a>
    </li>
    <li role="presentation" id="menuInstrumento"    data-function-handle="menu_instrumento">
        <a href="#" aria-controls="institucion" role="tab" data-toggle="tab">Instrumento</a>
    </li>
    <li role="presentation" id="menuReportes"       data-function-handle="menu_reportes">
        <a href="#" aria-controls="carreras" role="tab" data-toggle="tab">Preguntas frecuentes</a>
    </li>
</ul>