<style>
    .btn-primary{
        color: #FFF;
        background-color: #69C7C1;
        border-color: #69C7C1;
    }

    .btn-primary:hover, .btn-primary:focus, .btn-primary:active, .btn-primary.active, .open>.dropdown-toggle.btn-primary {
        color: #fff;
        background-color: #00A19C;
        border-color: #00A19C;
    }

    .btn {
        display: inline-block;
        padding: 6px 12px;
        margin-bottom: 0;
        font-size: 14px;
        font-weight: normal;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 1px;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
        transition: all 0.5s ease 0s;

    }
</style>
<div class="row">
    <div>
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li><a href="#">Instrumentos</a></li>
            <li class="active">Detalle</li>
        </ol>
    </div>    
</div>
<div class="row">
    <div class="tab-pane fade active in" id="responsable">
        <div class="tab-titulo">Consulta de instrumentos - Detalle</div>   
    </div>
</div>
<br>
<br>
<div class="form-group">
    <div class="col-md-6">
        <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">DRE:</label>
        <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
            <select name="lista_dre" id="lista_dre" class="form-control" style="margin-left: 15px;">
                <option value="">--Seleccione--</option>
            </select>
        </div>
    </div>
    <div class="col-md-6">
        <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">UGEL:</label>
        <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
            <select name="lista_ugel" id="lista_ugel" class="form-control" style="margin-left: 15px;">
                <option value="">--Seleccione--</option>
            </select>
        </div>
    </div>
</div>  
<br>
<br>
<div class="form-group">
    <div class="col-md-3">
        <label for="txttipoges" class="col-xs-3 col-sm-3 col-md-4 control-label">Institucion educativa</label>    
    </div>

    <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
        <div class="input-group">
            <input type="text" class="form-control" name="srch-iiee" id="srch-iiee">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </div>
</div>
<br>
<br>

<div  class="row">
    <div style="width: 800px !important;">
        <table id="grid_instrumentos_detail"></table>
        <div id="pager_grid_instrumentos_detail"></div>
    </div>
</div>
<?= file_get_contents(__DIR__ . '/formato_hb.html'); ?>

<div class="modal fade" id="modal_preguntas_tmp" aria-hidden="true" style="height: 700px;">
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Preguntas</h4>
            </div>
            <div class="modal-body">
                <div id="content_out">

                </div>
            </div>
        </div>
    </div>
</div>

