<style>
    .ui-jqgrid .ui-jqgrid-btable tbody tr.jqgrow td {
        white-space: normal !important;
        padding: 10px;
    }

    .ui-jqgrid .ui-jqgrid-htable .ui-th-div {
        height: 40px;
        margin-top: 5px;
        padding: 10px;
        display: list-item;
        background-color: #CAE7EA;
    }
    .ui-state-hover {
        border : 1px solid #CAE7EA;
        background: #14A3BD;
    }

    .ui-th-ltr, .ui-jqgrid .ui-jqgrid-htable th.ui-th-ltr {
        background-color: #CAE7EA;
    }
    .ui-state-highlight {
        background: #14A3BD;
    }
    .padd_input{
        padding-top:10px; padding-bottom: 30px;
    }

</style>
<div class="row">
    <div>
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li><a href="#">Instrumentos</a></li>
            <li class="active">Detalle</li>
        </ol>
    </div>    
</div>
<div class="row">
    <div class="tab-pane fade active in" id="responsable">
        <div class="tab-titulo">Consulta de instrumentos - Detalle</div>   
    </div>
</div>
<br>
<br>
<div class="form-group">
    <div class="col-md-6">
        <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">DRE:</label>
        <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
            <select name="lista_dre" id="lista_dre" class="form-control" style="margin-left: 15px;">
                <option value="">--Seleccione--</option>
            </select>
        </div>
    </div>
    <div class="col-md-6">
        <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">UGEL:</label>
        <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
            <select name="lista_ugel" id="lista_ugel" class="form-control" style="margin-left: 15px;">
                <option value="">--Seleccione--</option>
            </select>
        </div>
    </div>
</div>  
<br>
<br>
<div class="form-group">
    <label for="txttipoges" class="col-xs-3 col-sm-3 col-md-4 control-label">Institucion educativa</label>
    <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="srch-iiee" id="srch-iiee">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<div  class="row">
    <div class="col-md-6">
        <label>Informantes por instrumento</label>
    </div>
</div>
<div  class="row">
    <div class="col-md-6">
        <table id="grid_instrumentos_detail"></table>
        <div id="pager_grid_instrumentos_detail"></div>
    </div>
</div>
<?= file_get_contents(__DIR__ . '/formato_hb.html'); ?>

<div class="modal fade" id="modal_preguntas_tmp" aria-hidden="true">
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Preguntas</h4>
            </div>
            <div class="modal-body">
                <div id="content_out">

                </div>
            </div>
        </div>
    </div>
</div>

