<div class="row">
    <div>
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li class="active">Instrumentos</li>
        </ol>
    </div>    
</div>
<div class="row">
    <div class="tab-pane fade active in" id="responsable">
        <div class="tab-titulo">Consulta de instrumentos</div>
    </div>
</div>
<br>
<br>
<div class="row">
    <div style="width: 800px !important;">
        <table id="grid_instrumentos" ></table>
        <div id="pager_grid_instrumentos"></div>
    </div>
</div>