<style>
    .btn {
        display: inline-block;
        padding: 6px 12px;
        margin-bottom: 0;
        font-size: 14px;
        font-weight: normal;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 1px;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
        transition: all 0.5s ease 0s;

    }
    .btn-primary {
        background-color: #2962FF;
    }
    .btn-primary:hover, .btn-primary:focus {
        background-color: #0D47A1;
    }
</style>
<?php
$grupo_pregunta = $data['instrumento']['listaGrupoPregunta'];
?>
<div class="row">
    <div class="col col-sm-4">
        <ul class="nav nav-tabs nav-stacked text-center" role="tablist">
            <?php
            for ($i = 0; $i < count($grupo_pregunta); $i++)
            {
                $class = '';
                if ($i === 0)
                {
                    $class = 'class="active"';
                }
                $pasos = $i + 1;
                echo '<li role="presentation" ' . $class . '><a href="#paso_' . $pasos . '" aria-controls="paso_' . $pasos . '" role="tab" data-toggle="tab" style="font-size:12px; text-align:left;">' . $grupo_pregunta[$i]['nombre'] . '</a></li>';
            }
            ?>
        </ul>
    </div>    
    <div class="col col-sm-8">
        <div class="row tab-content">
            <?php
            $ppasos = 0;
            foreach ($grupo_pregunta as $grupo)
            {
                $ppasos++;
                $class = '';
                if ($ppasos === 1)
                {
                    $class = 'active in';
                }
                echo '<div role="tabpanel" class="tab-pane fade ' . $class . '" id="#paso_' . $ppasos . '">';
                foreach ($grupo['listaPreguntas'] as $preguntas)
                {
                    ?>
                    <div class="form-group" style="padding-top:10px; padding-bottom: 30px;">
                        <div class="col-md-9">
                            <label for="preg_<?php echo $preguntas['id_pregunta']; ?>"><?php echo $preguntas['id_pregunta'] . '.- ' . $preguntas['nombre']; ?></label>
                        </div>
                        <div class="col-md-3" style="text-align: center;">
                            <?php
                            switch (intval($preguntas['tipoPregunta']['id_tipo_pregunta']))
                            {
                                case 1:
                                    //1, Unica seleccion (Radiobuttons)
                                    echo '<div class="btn-group" data-toggle="buttons">';
                                    foreach ($preguntas['listaPreguntaOpcion'] as $opciones)
                                    {
                                        echo ' <label class="btn btn-primary"><input type="radio" name="opt' . $preguntas['id_pregunta'] . '" id="opt_' . $preguntas['id_pregunta'] . '_' . $opciones['id_pregunta_opcion'] . '"  value="' . $opciones['id_pregunta_opcion'] . '" autocomplete="off">' . $opciones['nombre'] . '</label>';
                                    }
                                    echo '</div>';
                                    break;
                                case 2:
                                    //2, Multiple seleccion (Checkbox)
                                    foreach ($preguntas['listaPreguntaOpcion'] as $opciones)
                                    {
                                        echo '<div class="checkbox">
                                            <label><input type="checkbox" id="opt_' . $preguntas['id_pregunta'] . '_' . $opciones['id_pregunta_opcion'] . '" value="' . $opciones['id_pregunta_opcion'] . '">' . $opciones['nombre'] . '</label>
                                          </div>';
                                    }
                                    break;
                                case 3:
                                    //3, Combo lista (ComboList)
                                    echo '<select name="slct_' . $preguntas['id_pregunta'] . '" id="slct_' . $preguntas['id_pregunta'] . '" class="form-control" style="margin-left: 15px;">';
                                    foreach ($preguntas['listaPreguntaOpcion'] as $opciones)
                                    {
                                        echo '<option value="' . $opciones['id_pregunta_opcion'] . '">' . $opciones['nombre'] . '</option>';
                                    }
                                    echo '</select>';
                                    break;
                                case 4:
                                    //4, Texto corto (texto hasta 100 caracteres)
                                    echo '<input type="text" name="inpt_' . $preguntas['id_pregunta'] . '" class="form-control" id="inpt_' . $preguntas['id_pregunta'] . '" maxlenght="100">';
                                    break;
                                case 5:
                                    //5, Texto extenso (texto multiple linea hasta 300 lineas)
                                    echo '<textarea class="form-control" name="inpt_mult' . $preguntas['id_pregunta'] . '" id="inpt_mult_' . $preguntas['id_pregunta'] . '" rows="3" maxlenght="300"></textarea>';
                                    break;
                                case 6:
                                    //6, Escala lineal (es de calificacion ejmp de 0 a 5 calificacion de atencion )

                                    echo 'Por definir.';

                                    break;
                                case 7:
                                    //7, Fecha ( para ingresar fecha)
                                    echo '<input class="form-control" type="datetime-local" value="2011-08-19T13:45:00" id="example-datetime-local-input">';
                                    break;
                            }
                            ?>
                        </div>
                    </div>
                    <?php
                }
                echo '</div>';
            }
            ?>
        </div>
    </div>
</div>

<div class="row">
    <ul class="list-inline pull-right">
        <li><button type="button" class="btn btn-default prev-step">Previo</button></li>
        <li><button type="button" class="btn btn-default next-step">Siguiente</button></li>
        <!--<li><button type="button" class="btn btn-primary ">Save</button></li>-->
    </ul>                
</div>