<div class="row">
    <div>
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li class="active">Preguntas frecuentes</li>
        </ol>
    </div>    
</div>
<div class="row">
    <div class="tab-pane fade active in" id="responsable">
        <div class="tab-titulo">Preguntas frecuentes</div>
    </div>
</div>
<?= file_get_contents(__DIR__ . '/formato_pf.html'); ?>
<br>
<br>
<div id="content_out"></div>
